/** Every diagnostic this package can raise; a code is stable and greppable, so it is API. */
export const CODE = {
  unnamedFile: 'loader.unnamed-file',
  notAMapping: 'loader.not-a-mapping',
  notASequence: 'loader.not-a-sequence',
  notText: 'loader.not-text',
  notABoolean: 'loader.not-a-boolean',
  notANumber: 'loader.not-a-number',
  notAValue: 'loader.not-a-value',
  duplicateKey: 'loader.duplicate-key',
  unknownKey: 'loader.unknown-key',
  missingKey: 'loader.missing-key',
  emptyCell: 'loader.empty-cell',
  conflictingKeys: 'loader.conflicting-keys',
  badAddress: 'loader.bad-address',
  badRange: 'loader.bad-range',
  badColumn: 'loader.bad-column',
  badRow: 'loader.bad-row',
  badColor: 'loader.bad-color',
  badName: 'loader.bad-name',
  badPath: 'loader.bad-path',
  unknownSpelling: 'loader.unknown-spelling',
  includeNotExpanded: 'loader.include-not-expanded',
  includeWithSiblings: 'loader.include-with-siblings',
  includeUnreadable: 'loader.include-unreadable',
  includeCycle: 'loader.include-cycle',
  includeEmpty: 'loader.include-empty',
} as const;

export type Code = (typeof CODE)[keyof typeof CODE];
